CREATE DATABASE HROADS;
GO

USE HROADS;
GO

CREATE TABLE PERSONAGEM (
	idPersonagem TINYINT PRIMARY KEY IDENTITY(1,1),
	idClasseHabi TINYINT FOREIGN KEY REFERENCES CLASSEHABILIDADE(idClasseHabi),
	nomePersonagem VARCHAR(15) NOT NULL UNIQUE,
	qtdMaxVida TINYINT NOT NULL UNIQUE,
	qtdMaxMana TINYINT NOT NULL UNIQUE,
	dataAtualizacao DATE NOT NULL,
	dataCriacao DATE NOT NULL 
);
GO

CREATE TABLE CLASSEHABILIDADE (
	idClasseHabi TINYINT PRIMARY KEY IDENTITY(1,1),
	idClasse TINYINT FOREIGN KEY REFERENCES CLASSE(idClasse),
	idHabilidade TINYINT FOREIGN KEY REFERENCES HABILIDADE(idHabilidade)
);
GO

CREATE TABLE CLASSE (
	idClasse TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeClasse VARCHAR(20) NOT NULL UNIQUE
);
GO

CREATE TABLE HABILIDADE (
	idHabilidade TINYINT PRIMARY KEY IDENTITY(1,1),
	idTipoHabilidade TINYINT FOREIGN KEY REFERENCES TIPOHABILIDADE(idTipoHabilidade),
	nomeHabilidade VARCHAR(20) NOT NULL UNIQUE
);
GO

CREATE TABLE TIPOHABILIDADE (
	idTipoHabilidade TINYINT PRIMARY KEY IDENTITY(1,1),
	tipoHabilidade VARCHAR(20) NOT NULL,
	valor TINYINT NOT NULL
);
GO